class StoryConstants {
    static possibleSubjects: Array<string> = [
        "Matemática",
        "Física",
        "Química",
        "Biologia",
        "Geologia",
        "Astronomia",
        "Ciência da Computação",
        "Estatística",
        "Química Orgânica",
        "Microbiologia",
        "Neurociência",
        "Engenharia",
        "Ecologia",
        "Ciência dos Materiais",
        "Psicologia",
        "Economia",
        "História da Ciência",
        "Ética Científica",
        "Filosofia da Ciência",
        "Comunicação Científica"
    ];

    static possibleCharacters: Array<string> = [
        "Leão",
        "Raposa",
        "Coruja",
        "Coelho",
        "Tartaruga",
        "Cão",
        "Gato",
        "Rato",
        "Pássaro",
        "Galinha",
        "Peixe",
        "Elefante",
        "Cervo",
        "Tartaruga",
        "Abelha",
        "Formiga",
        "Leopardo",
        "Urso",
        "Girafa",
        "Camundongo",
        "Sapo",
        "Lontra",
        "Borboleta",
        "Pinguim",
        "Pavão",
        "Pardal",
        "Cobra",
        "Jacaré",
        "Bode",
        "Burro",
    ];
}

export default StoryConstants;